/*
 * Machine files the Tamga server actually produced.
 *
 * Every other machine-file fixture in this repository was generated by
 * tools/fixture-generator/ -- by us, for us -- and each one reproduced this
 * SDK's own misreading of the format. CI stayed green for two years while no
 * build here could open a single file the server emitted: `alg` carries a
 * mandatory `+v2` segment that the verifier's suffix comparison rejected, and
 * an encrypted payload is two separately base64-encoded halves rather than one
 * blob. A fixture we mint ourselves cannot catch either.
 *
 * These came out of the server's own `encode_machine_file` -- see
 * tests/fixtures/server-machine-files/README.md -- and the set is driven from
 * its manifest.json rather than from names written into this file, so a
 * fixture added to that directory is exercised here without an edit.
 *
 * ⚠️ Every assertion below supplies its own `now`. The "valid" fixtures were
 * issued with a one-hour ttl, so anything checked against the wall clock stops
 * passing an hour after the fixtures were generated. Each fixture's own signed
 * `iat`/`exp` are the only stable reference points, and they are read back out
 * of the file rather than written down here.
 */
#include "tamga_test.h"

#include "checkout/cert.h"
#include "checkout/claims.h"
#include "checkout/machine_file.h"
#include "checkout/pem.h"
#include "tamga_error.h"
#include "tamga_mem.h"
#include "util/base64.h"
#include "util/json.h"

#define FILE_CAP 8192
#define KEY_CAP 1024
#define MANIFEST_CAP 65536
#define FIXTURE_DIR "server-machine-files"

/*
 * A clock reading before every possible expiry, so the expiry check cannot
 * fire. It is how the signed claims are harvested out of every fixture --
 * including the ones issued already expired, whose signature is perfectly
 * good and whose `exp` is the thing under test.
 */
#define BEFORE_ANY_EXPIRY 0

static const char MACHINE_PEM_BEGIN[] = "-----BEGIN MACHINE FILE-----";
static const char MACHINE_PEM_END[] = "-----END MACHINE FILE-----";

typedef struct Fixture {
    const char *name;
    const char *file;
    const char *alg;
    const char *license_key; /* NULL for a plain file */
    const char *fingerprint;
    bool encrypted;
    bool enc_is_dot_separated;
    bool expired;
    uint32_t scheme;
} Fixture;

/* Reports one failure with the fixture it belongs to. */
static void fail(const Fixture *fixture, const char *detail) {
    tt_failures_++;
    (void)fprintf(stderr, "FAIL %s: %s -- %s (%s)\n", tt_current_, fixture->name, detail,
                  tamga_last_error_message() ? tamga_last_error_message() : "");
}

/*
 * The manifest names schemes the way the server's Rust enum does. An
 * unrecognised name is a hard failure rather than a skip: a fixture nobody
 * ran is indistinguishable from one that passed, which is the failure mode
 * this whole file exists to close.
 */
static bool scheme_from_name(const char *name, uint32_t *out) {
    static const struct {
        const char *name;
        uint32_t scheme;
    } NAMES[] = {
        {"Ed25519Sign", (uint32_t)TAMGA_SCHEME_ED25519_SIGN},
        {"ED25519_SIGN", (uint32_t)TAMGA_SCHEME_ED25519_SIGN},
        {"Rsa2048Pkcs1Sign", (uint32_t)TAMGA_SCHEME_RSA_2048_PKCS1_SIGN},
        {"RSA_2048_PKCS1_SIGN", (uint32_t)TAMGA_SCHEME_RSA_2048_PKCS1_SIGN},
        {"Rsa2048Pkcs1PssSign", (uint32_t)TAMGA_SCHEME_RSA_2048_PKCS1_PSS_SIGN},
        {"RSA_2048_PKCS1_PSS_SIGN", (uint32_t)TAMGA_SCHEME_RSA_2048_PKCS1_PSS_SIGN},
        {"EcdsaP256Sign", (uint32_t)TAMGA_SCHEME_ECDSA_P256_SIGN},
        {"ECDSA_P256_SIGN", (uint32_t)TAMGA_SCHEME_ECDSA_P256_SIGN},
    };
    size_t i;

    if (name == NULL) {
        return false;
    }
    for (i = 0u; i < (sizeof(NAMES) / sizeof(NAMES[0])); i++) {
        if (strcmp(name, NAMES[i].name) == 0) {
            *out = NAMES[i].scheme;
            return true;
        }
    }
    return false;
}

/* Any scheme whose alg suffix differs from this one, for the cross-check that
 * a file issued for one scheme does not verify when the licence claims
 * another. */
static uint32_t a_different_scheme(uint32_t scheme) {
    if (scheme == (uint32_t)TAMGA_SCHEME_ED25519_SIGN) {
        return (uint32_t)TAMGA_SCHEME_ECDSA_P256_SIGN;
    }
    return (uint32_t)TAMGA_SCHEME_ED25519_SIGN;
}

static const char *manifest_string(const TamgaJson *entry, const char *key) {
    const TamgaJson *value = tamga_json_object_get(entry, key);
    if (value == NULL || tamga_json_is_null(value)) {
        return NULL;
    }
    return tamga_json_as_string(value, NULL);
}

static bool manifest_bool(const TamgaJson *entry, const char *key) {
    return tamga_json_bool_or(tamga_json_object_get(entry, key), false);
}

static bool fixture_from_manifest(const char *name, const TamgaJson *entry, Fixture *out) {
    out->name = (name != NULL) ? name : "(unnamed)";
    out->file = manifest_string(entry, "file");
    out->alg = manifest_string(entry, "alg");
    out->license_key = manifest_string(entry, "license_key");
    out->fingerprint = manifest_string(entry, "fingerprint");
    out->encrypted = manifest_bool(entry, "encrypted");
    out->enc_is_dot_separated = manifest_bool(entry, "enc_is_dot_separated");
    out->expired = manifest_bool(entry, "expired");
    return out->file != NULL && out->alg != NULL &&
           scheme_from_name(manifest_string(entry, "scheme"), &out->scheme);
}

/* Reads <FIXTURE_DIR>/<name> into `out`. */
static size_t read_fixture_file(const char *name, unsigned char *out, size_t cap) {
    char relative[512];
    if (snprintf(relative, sizeof(relative), "%s/%s", FIXTURE_DIR, name) < 0) {
        return (size_t)-1;
    }
    return tt_read_fixture(relative, out, cap);
}

static TamgaJson *load_manifest(void) {
    static unsigned char raw[MANIFEST_CAP];
    size_t raw_len = read_fixture_file("manifest.json", raw, sizeof(raw));
    if (raw_len == (size_t)-1) {
        return NULL;
    }
    return tamga_json_parse((const char *)raw, raw_len, NULL);
}

/* --- verification helpers ------------------------------------------------ */

/* Verifies and reports only the status; any resource produced is freed here. */
static TamgaErrorCode verify(const char *pem, size_t pem_len, uint32_t scheme,
                             const unsigned char *pubkey, size_t pubkey_len,
                             const char *license_key, const char *fingerprint, int64_t now_unix) {
    TamgaJson *resource = NULL;
    TamgaErrorCode status =
        tamga_machine_file_verify_at(pem, pem_len, scheme, pubkey, pubkey_len, license_key,
                                     fingerprint, now_unix, &resource, NULL);
    if (status != TAMGA_OK && resource != NULL) {
        /* Every failure path must leave the out-parameter untouched, or a
         * caller that only checks the pointer gets a half-built answer. */
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: a failing verify still wrote a resource\n", tt_current_);
    }
    tamga_json_free(resource);
    return status;
}

static void expect(const Fixture *fixture, const char *what, TamgaErrorCode actual,
                   TamgaErrorCode expected) {
    if (actual != expected) {
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: %s -- %s: expected %s, got %s (%s)\n", tt_current_,
                      fixture->name, what, tamga_error_name(expected), tamga_error_name(actual),
                      tamga_last_error_message() ? tamga_last_error_message() : "");
    }
}

/* --- what the bytes on disk actually say -------------------------------- */

/*
 * The manifest is a description; this checks it against the file. Reading
 * `alg` and `enc` straight out of the certificate also pins the two wire
 * facts this round is about -- the "+v2" segment and the dot-separated
 * encrypted payload -- independently of the verifier that is supposed to
 * understand them.
 */
static void the_file_matches_its_manifest_entry(const Fixture *fixture, const TamgaCert *cert) {
    bool has_dot;

    if (!tamga_cert_alg_equals(cert, fixture->alg, strlen(fixture->alg))) {
        fail(fixture, "the file declares an alg the manifest does not");
    }
    /* The server writes "<encoding>+<signing suffix>+v2" and nothing else. */
    if (cert->alg_len < 3u || memcmp(&cert->alg[cert->alg_len - 3u], "+v2", 3u) != 0) {
        fail(fixture, "the declared alg does not end in +v2");
    }
    has_dot = memchr(cert->enc, '.', cert->enc_len) != NULL;
    if (has_dot != fixture->enc_is_dot_separated) {
        fail(fixture, "the enc separator does not match the manifest");
    }
}

/* --- rebuilding a certificate with one field altered --------------------- */

/*
 * Writes a MACHINE FILE PEM around the three given fields.
 *
 * None of them can contain a JSON metacharacter -- two are base64 and the
 * third is the alg vocabulary -- so this concatenates rather than escaping,
 * which keeps the bytes it produces exactly predictable. Returns the length,
 * or SIZE_MAX if anything did not fit.
 */
static size_t build_machine_pem(const char *enc, size_t enc_len, const char *sig, size_t sig_len,
                                const char *alg, size_t alg_len, char *out, size_t out_cap) {
    static char json[FILE_CAP];
    char *encoded;
    size_t json_len = 0u;
    size_t written = 0u;
    size_t encoded_len;

    if ((enc_len + sig_len + alg_len + 64u) > sizeof(json)) {
        return (size_t)-1;
    }

#define APPEND_LITERAL(text)                                                                       \
    do {                                                                                           \
        memcpy(&json[json_len], (text), sizeof(text) - 1u);                                        \
        json_len += sizeof(text) - 1u;                                                             \
    } while (0)
#define APPEND_SPAN(ptr, len)                                                                      \
    do {                                                                                           \
        memcpy(&json[json_len], (ptr), (len));                                                     \
        json_len += (len);                                                                         \
    } while (0)

    APPEND_LITERAL("{\"enc\":\"");
    APPEND_SPAN(enc, enc_len);
    APPEND_LITERAL("\",\"sig\":\"");
    APPEND_SPAN(sig, sig_len);
    APPEND_LITERAL("\",\"alg\":\"");
    APPEND_SPAN(alg, alg_len);
    APPEND_LITERAL("\"}");

#undef APPEND_LITERAL
#undef APPEND_SPAN

    encoded = tamga_base64_encode_alloc((const unsigned char *)json, json_len);
    if (encoded == NULL) {
        return (size_t)-1;
    }
    encoded_len = strlen(encoded);
    if ((sizeof(MACHINE_PEM_BEGIN) + encoded_len + sizeof(MACHINE_PEM_END) + 4u) > out_cap) {
        tamga_free(encoded);
        return (size_t)-1;
    }
    memcpy(&out[written], MACHINE_PEM_BEGIN, sizeof(MACHINE_PEM_BEGIN) - 1u);
    written += sizeof(MACHINE_PEM_BEGIN) - 1u;
    out[written++] = '\n';
    memcpy(&out[written], encoded, encoded_len);
    written += encoded_len;
    out[written++] = '\n';
    memcpy(&out[written], MACHINE_PEM_END, sizeof(MACHINE_PEM_END) - 1u);
    written += sizeof(MACHINE_PEM_END) - 1u;
    out[written] = '\0';
    tamga_free(encoded);
    return written;
}

/*
 * The same file, rewritten one field at a time. The signature still covers the
 * original `enc`, so each rejection below can only be the check it names.
 */
static void the_altered_certificates_are_rejected(const Fixture *fixture, const TamgaCert *cert,
                                                  const unsigned char *pubkey, size_t pubkey_len) {
    static char scratch[FILE_CAP];
    static char altered[FILE_CAP];
    size_t altered_len;
    size_t i;
    static const char *const BAD_TAILS[] = {"", "+v1", "+v3", "+v2junk", "+v2+v2"};

    if ((cert->enc_len + 8u) > sizeof(scratch) || (cert->alg_len + 8u) > sizeof(scratch) ||
        cert->alg_len < 3u) {
        fail(fixture, "the certificate is too large to rewrite in this harness");
        return;
    }

    /* A tampered enc fails on the signature. One flipped base64 character is
     * enough. */
    memcpy(scratch, cert->enc, cert->enc_len);
    scratch[0] = (scratch[0] == 'A') ? 'B' : 'A';
    altered_len = build_machine_pem(scratch, cert->enc_len, cert->sig, cert->sig_len, cert->alg,
                                    cert->alg_len, altered, sizeof(altered));
    if (altered_len == (size_t)-1) {
        fail(fixture, "could not rebuild the certificate");
        return;
    }
    expect(fixture, "with a flipped byte in enc",
           verify(altered, altered_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                  fixture->fingerprint, BEFORE_ANY_EXPIRY),
           TAMGA_ERR_SIGNATURE_INVALID);

    /* And the ordering: enc is verified BEFORE it is decoded. This payload is
     * not base64 at all, so a verifier that decoded first would answer
     * INVALID_BASE64 -- or, for an encrypted file, fail in the split --
     * instead of SIGNATURE_INVALID. Never parse bytes an attacker chose before
     * checking who signed them. */
    memcpy(scratch, cert->enc, cert->enc_len);
    memcpy(&scratch[cert->enc_len], "!!!", 3u);
    altered_len = build_machine_pem(scratch, cert->enc_len + 3u, cert->sig, cert->sig_len,
                                    cert->alg, cert->alg_len, altered, sizeof(altered));
    if (altered_len == (size_t)-1) {
        fail(fixture, "could not rebuild the certificate");
        return;
    }
    expect(fixture, "with an unparseable enc",
           verify(altered, altered_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                  fixture->fingerprint, BEFORE_ANY_EXPIRY),
           TAMGA_ERR_SIGNATURE_INVALID);

    /* The two ways an encrypted payload's framing can be wrong, both still
     * answered on the SIGNATURE and not on the framing.
     *
     * This SDK's base64 decoder rejects any character outside the alphabet --
     * TAMGA_B64_REVERSE['.'] is 0xFF -- so the '.' is not silently dropped the
     * way a lenient decoder would drop it, and the old single-blob reading was
     * an outright failure here rather than an accident that happened to work.
     * The split itself is unreachable without a valid signature, which is the
     * property these two assert: a verifier that split first would answer
     * DECRYPTION_FAILED instead. */
    if (fixture->enc_is_dot_separated) {
        const char *dot = (const char *)memchr(cert->enc, '.', cert->enc_len);
        size_t head_len;

        if (dot == NULL) {
            fail(fixture, "the manifest says dot-separated but the enc has no separator");
            return;
        }
        head_len = (size_t)(dot - cert->enc);

        /* The separator removed: nonce and ciphertext as one blob, which is
         * what every SDK in this family used to expect. */
        memcpy(scratch, cert->enc, head_len);
        memcpy(&scratch[head_len], dot + 1, cert->enc_len - head_len - 1u);
        altered_len = build_machine_pem(scratch, cert->enc_len - 1u, cert->sig, cert->sig_len,
                                        cert->alg, cert->alg_len, altered, sizeof(altered));
        if (altered_len == (size_t)-1) {
            fail(fixture, "could not rebuild the certificate");
            return;
        }
        expect(fixture, "with the separator removed",
               verify(altered, altered_len, fixture->scheme, pubkey, pubkey_len,
                      fixture->license_key, fixture->fingerprint, BEFORE_ANY_EXPIRY),
               TAMGA_ERR_SIGNATURE_INVALID);

        /* A second separator. */
        memcpy(scratch, cert->enc, cert->enc_len);
        scratch[cert->enc_len] = '.';
        altered_len = build_machine_pem(scratch, cert->enc_len + 1u, cert->sig, cert->sig_len,
                                        cert->alg, cert->alg_len, altered, sizeof(altered));
        if (altered_len == (size_t)-1) {
            fail(fixture, "could not rebuild the certificate");
            return;
        }
        expect(fixture, "with a second separator",
               verify(altered, altered_len, fixture->scheme, pubkey, pubkey_len,
                      fixture->license_key, fixture->fingerprint, BEFORE_ANY_EXPIRY),
               TAMGA_ERR_SIGNATURE_INVALID);
    }

    /* The +v2 marker is mandatory, and only "+v2" is it. A v1 payload carried
     * no signed exp and derived its AES key by zero-padding the licence key;
     * accepting one reinstates both weaknesses. A substring test would let
     * "+v2junk" and "+v3" through. */
    for (i = 0u; i < (sizeof(BAD_TAILS) / sizeof(BAD_TAILS[0])); i++) {
        size_t stem_len = cert->alg_len - 3u; /* drop the real "+v2" */
        size_t tail_len = strlen(BAD_TAILS[i]);

        memcpy(scratch, cert->alg, stem_len);
        memcpy(&scratch[stem_len], BAD_TAILS[i], tail_len);
        altered_len = build_machine_pem(cert->enc, cert->enc_len, cert->sig, cert->sig_len, scratch,
                                        stem_len + tail_len, altered, sizeof(altered));
        if (altered_len == (size_t)-1) {
            fail(fixture, "could not rebuild the certificate");
            return;
        }
        expect(fixture, "with a rewritten version marker",
               verify(altered, altered_len, fixture->scheme, pubkey, pubkey_len,
                      fixture->license_key, fixture->fingerprint, BEFORE_ANY_EXPIRY),
               TAMGA_ERR_UNSUPPORTED_SCHEME);
    }
}

/* --- the per-fixture battery -------------------------------------------- */

static void run_fixture(const Fixture *fixture, const char *public_key_b64) {
    static char pem[FILE_CAP];
    unsigned char pubkey[KEY_CAP];
    size_t pem_len;
    size_t pubkey_len = 0u;
    unsigned char *decoded_key;
    TamgaJson *resource = NULL;
    TamgaFileClaims claims;
    TamgaErrorCode status;
    char *body = NULL;
    size_t body_len = 0u;
    TamgaCert cert;
    const char *type;

    pem_len = read_fixture_file(fixture->file, (unsigned char *)pem, sizeof(pem) - 1u);
    if (pem_len == (size_t)-1) {
        fail(fixture, "the fixture file could not be read");
        return;
    }
    pem[pem_len] = '\0';

    decoded_key = tamga_base64_decode_alloc(public_key_b64, strlen(public_key_b64), &pubkey_len);
    if (decoded_key == NULL || pubkey_len == 0u || pubkey_len > sizeof(pubkey)) {
        fail(fixture, "the manifest's public key did not decode");
        tamga_free(decoded_key);
        return;
    }
    memcpy(pubkey, decoded_key, pubkey_len);
    tamga_free(decoded_key);

    /* 1. It verifies at all -- signature, alg, decryption, payload. This is
     *    the assertion no build of this SDK could make before, for any real
     *    file, under any scheme. */
    status = tamga_machine_file_verify_at(pem, pem_len, fixture->scheme, pubkey, pubkey_len,
                                          fixture->license_key, fixture->fingerprint,
                                          BEFORE_ANY_EXPIRY, &resource, &claims);
    if (status != TAMGA_OK) {
        fail(fixture, "the file the server signed did not verify");
        return;
    }
    type = tamga_json_as_string(tamga_json_object_get(resource, "type"), NULL);
    if (type == NULL || strcmp(type, "machines") != 0) {
        fail(fixture, "the payload did not decode to a machine resource");
    }
    tamga_json_free(resource);

    /* 2. The signed claims are read, not ignored. `iat` is always present;
     *    `exp` is optional by design, and a file issued without a ttl
     *    genuinely never expires. */
    if (claims.issued_at <= 0) {
        fail(fixture, "the payload carries no signed iat");
    }

    if (claims.has_expiry) {
        /* 3. The manifest's own verdict, at the file's issuance time. A file
         *    issued already-expired is refused as EXPIRED, distinctly from a
         *    signature failure -- "fetch a fresh one" and "this is forged"
         *    are different answers. */
        expect(fixture, "at its own iat",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                      fixture->fingerprint, claims.issued_at),
               fixture->expired ? TAMGA_ERR_EXPIRED : TAMGA_OK);

        /* 4. The tolerance is 60 seconds, and it is the same 60 seconds the
         *    licence-file path uses -- both run through
         *    tamga_claims_are_expired(). */
        expect(fixture, "at exp",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                      fixture->fingerprint, claims.expiry),
               TAMGA_OK);
        expect(fixture, "at exp + tolerance",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                      fixture->fingerprint, claims.expiry + TAMGA_CLOCK_SKEW_TOLERANCE_SECONDS),
               TAMGA_OK);
        expect(fixture, "one second past the tolerance",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                      fixture->fingerprint, claims.expiry + TAMGA_CLOCK_SKEW_TOLERANCE_SECONDS + 1),
               TAMGA_ERR_EXPIRED);
    } else if (fixture->expired) {
        fail(fixture, "the manifest marks this expired but the payload carries no exp");
    }

    /* 5. The scheme comes from the caller. The same bytes must not verify
     *    under a scheme whose alg suffix they do not declare, and
     *    RSA_2048_JWT_RS256 is refused before anything is parsed at all. */
    expect(fixture, "under a different scheme",
           verify(pem, pem_len, a_different_scheme(fixture->scheme), pubkey, pubkey_len,
                  fixture->license_key, fixture->fingerprint, BEFORE_ANY_EXPIRY),
           TAMGA_ERR_UNSUPPORTED_SCHEME);
    expect(fixture, "under RSA_2048_JWT_RS256",
           verify(pem, pem_len, (uint32_t)TAMGA_SCHEME_RSA_2048_JWT_RS256, pubkey, pubkey_len,
                  fixture->license_key, fixture->fingerprint, BEFORE_ANY_EXPIRY),
           TAMGA_ERR_UNSUPPORTED_SCHEME);

    /* 6. An encrypted file is bound to one machine: the key derivation folds
     *    in the fingerprint, so holding the licence key is not enough. */
    if (fixture->encrypted) {
        expect(fixture, "with another machine's fingerprint",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key,
                      "a-different-fingerprint", BEFORE_ANY_EXPIRY),
               TAMGA_ERR_DECRYPTION_FAILED);
        expect(fixture, "with the licence key alone",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, fixture->license_key, NULL,
                      BEFORE_ANY_EXPIRY),
               TAMGA_ERR_NULL_ARGUMENT);
        expect(fixture, "with the wrong licence key",
               verify(pem, pem_len, fixture->scheme, pubkey, pubkey_len, "WRONG-KEY",
                      fixture->fingerprint, BEFORE_ANY_EXPIRY),
               TAMGA_ERR_DECRYPTION_FAILED);
    }

    /* 7. The wire format itself, and the same file with one field rewritten. */
    if (tamga_pem_extract(pem, pem_len, MACHINE_PEM_BEGIN, MACHINE_PEM_END, &body, &body_len) !=
        TAMGA_OK) {
        fail(fixture, "the PEM envelope did not parse");
        return;
    }
    status = tamga_cert_parse(body, body_len, &cert);
    tamga_string_free(body);
    if (status != TAMGA_OK) {
        fail(fixture, "the certificate did not parse");
        return;
    }
    the_file_matches_its_manifest_entry(fixture, &cert);
    the_altered_certificates_are_rejected(fixture, &cert, pubkey, pubkey_len);
    tamga_cert_free(&cert);
}

/* --- the manifest ------------------------------------------------------- */

TT_TEST(every_fixture_the_server_produced) {
    TamgaJson *manifest = load_manifest();
    size_t count;
    size_t i;

    TT_ASSERT_NOT_NULL(manifest);
    if (tamga_json_type(manifest) != TAMGA_JSON_OBJECT) {
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: the manifest is not an object\n", tt_current_);
        tamga_json_free(manifest);
        return;
    }

    count = tamga_json_object_len(manifest);
    if (count == 0u) {
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: the manifest is empty\n", tt_current_);
    }

    for (i = 0u; i < count; i++) {
        const char *name = tamga_json_object_key_at(manifest, i);
        const TamgaJson *entry = tamga_json_object_value_at(manifest, i);
        const char *public_key_b64 = manifest_string(entry, "public_key_b64");
        Fixture fixture;

        if (!fixture_from_manifest(name, entry, &fixture) || public_key_b64 == NULL) {
            tt_failures_++;
            (void)fprintf(stderr,
                          "FAIL %s: manifest entry \"%s\" is incomplete, or names a scheme "
                          "this SDK does not know\n",
                          tt_current_, (name != NULL) ? name : "(null)");
            continue;
        }
        run_fixture(&fixture, public_key_b64);
    }

    tamga_json_free(manifest);
}

/*
 * All four schemes must actually be present. Without this the suite still
 * passes if the manifest shrinks to a single Ed25519 entry -- and Ed25519 is
 * the one signing suffix with no hyphen in it, so a parser that split on the
 * wrong delimiter would look healthy.
 */
TT_TEST(the_manifest_covers_every_scheme_and_both_encodings) {
    TamgaJson *manifest = load_manifest();
    size_t count;
    size_t i;
    bool seen_scheme[6];
    bool seen_encrypted = false;
    bool seen_plain = false;
    bool seen_expired = false;

    memset(seen_scheme, 0, sizeof(seen_scheme));
    TT_ASSERT_NOT_NULL(manifest);

    count = tamga_json_object_len(manifest);
    for (i = 0u; i < count; i++) {
        const TamgaJson *entry = tamga_json_object_value_at(manifest, i);
        Fixture fixture;

        if (!fixture_from_manifest(tamga_json_object_key_at(manifest, i), entry, &fixture)) {
            continue;
        }
        if (fixture.scheme < (sizeof(seen_scheme) / sizeof(seen_scheme[0]))) {
            seen_scheme[fixture.scheme] = true;
        }
        seen_encrypted = seen_encrypted || fixture.encrypted;
        seen_plain = seen_plain || !fixture.encrypted;
        seen_expired = seen_expired || fixture.expired;
    }
    tamga_json_free(manifest);

    TT_ASSERT(seen_scheme[TAMGA_SCHEME_ED25519_SIGN]);
    TT_ASSERT(seen_scheme[TAMGA_SCHEME_RSA_2048_PKCS1_SIGN]);
    TT_ASSERT(seen_scheme[TAMGA_SCHEME_RSA_2048_PKCS1_PSS_SIGN]);
    TT_ASSERT(seen_scheme[TAMGA_SCHEME_ECDSA_P256_SIGN]);
    TT_ASSERT(seen_encrypted);
    TT_ASSERT(seen_plain);
    TT_ASSERT(seen_expired);
}

/*
 * The one thing the loop above cannot say on its own: the alg suffix cannot
 * identify the scheme, because the server emits "rsa-sha256" for both
 * RSA_2048_PKCS1_SIGN and RSA_2048_JWT_RS256. Same bytes, same key, two
 * caller-supplied schemes, two different answers -- which is the proof that
 * the scheme parameter is authoritative and the file's alg is a cross-check.
 */
TT_TEST(the_alg_suffix_cannot_choose_the_scheme) {
    static char pem[FILE_CAP];
    unsigned char pubkey[KEY_CAP];
    unsigned char *decoded;
    size_t pem_len;
    size_t pubkey_len = 0u;
    TamgaJson *manifest = load_manifest();
    const TamgaJson *entry;
    const char *file;
    const char *public_key_b64;
    TamgaJson *resource = NULL;

    TT_ASSERT_NOT_NULL(manifest);
    entry = tamga_json_object_get(manifest, "rsa_pkcs1_plain_valid");
    file = manifest_string(entry, "file");
    public_key_b64 = manifest_string(entry, "public_key_b64");
    if (file == NULL || public_key_b64 == NULL) {
        /* The manifest is allowed to grow; say so rather than passing
         * silently on a fixture that is no longer there. */
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: no usable rsa_pkcs1_plain_valid entry in the manifest\n",
                      tt_current_);
        tamga_json_free(manifest);
        return;
    }

    pem_len = read_fixture_file(file, (unsigned char *)pem, sizeof(pem));
    decoded = tamga_base64_decode_alloc(public_key_b64, strlen(public_key_b64), &pubkey_len);
    tamga_json_free(manifest);
    if (pem_len == (size_t)-1 || decoded == NULL || pubkey_len > sizeof(pubkey)) {
        tt_failures_++;
        (void)fprintf(stderr, "FAIL %s: could not load the RSA PKCS#1 fixture\n", tt_current_);
        tamga_free(decoded);
        return;
    }
    memcpy(pubkey, decoded, pubkey_len);
    tamga_free(decoded);

    TT_ASSERT_EQ_INT(tamga_machine_file_verify_at(
                         pem, pem_len, (uint32_t)TAMGA_SCHEME_RSA_2048_PKCS1_SIGN, pubkey,
                         pubkey_len, NULL, NULL, BEFORE_ANY_EXPIRY, &resource, NULL),
                     TAMGA_OK);
    tamga_json_free(resource);
    resource = NULL;

    TT_ASSERT_EQ_INT(tamga_machine_file_verify_at(
                         pem, pem_len, (uint32_t)TAMGA_SCHEME_RSA_2048_JWT_RS256, pubkey,
                         pubkey_len, NULL, NULL, BEFORE_ANY_EXPIRY, &resource, NULL),
                     TAMGA_ERR_UNSUPPORTED_SCHEME);
    TT_ASSERT_NULL(resource);
}

int main(void) {
    TT_RUN(every_fixture_the_server_produced);
    TT_RUN(the_manifest_covers_every_scheme_and_both_encodings);
    TT_RUN(the_alg_suffix_cannot_choose_the_scheme);
    return TT_SUMMARY();
}
