/*
 * tamga.h -- C ABI for the Tamga licensing SDK.
 *
 * Hand-maintained. Through v1.2.x this file was generated by cbindgen from a
 * Rust crate that wrapped tamga-rust; as of v1.3.0 the library is a native,
 * dependency-free C implementation and this header is the source of truth for
 * its ABI. The declarations below are byte-for-byte signature-compatible with
 * the v1.2.2 header -- a binary built against that header links and runs
 * against this one unchanged.
 *
 * ABI stability policy: once a version of this header has shipped in a GitHub
 * Release, struct layout and function signature changes require a version
 * bump -- no silent breaking changes. Enum values are appended, never
 * renumbered.
 *
 * Alloc/free pairing contract: every function that returns an owned pointer
 * has exactly one matching tamga_*_free. Every owned `char *` this library
 * returns (JSON payloads, proof strings) must be released via
 * tamga_string_free -- never libc free(). Double-free is documented undefined
 * behavior and intentionally unguarded; guarding it would hide caller bugs.
 *
 * Dependencies: none. The offline-verification surface below links against
 * the C standard library and nothing else. The HTTP client surface
 * additionally needs a transport, which is either an operating-system
 * component (WinHTTP on Windows, libcurl elsewhere) or one the caller
 * supplies -- see tamga_client_set_transport.
 *
 * Thread safety: every function is safe to call concurrently from multiple
 * threads on distinct handles. The last-error slot behind
 * tamga_last_error_message is per-thread. A single handle must not be used
 * concurrently from two threads without external synchronisation.
 */

#ifndef TAMGA_H
#define TAMGA_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Export/import decoration. Consumers of the static library must define
 * TAMGA_STATIC_LIB (the CMake target does this for you via a PUBLIC compile
 * definition); consumers of the DLL must not.
 */
#if defined(_WIN32) && !defined(TAMGA_STATIC_LIB)
#if defined(TAMGA_BUILD_SHARED_LIB)
#define TAMGA_API __declspec(dllexport)
#else
#define TAMGA_API __declspec(dllimport)
#endif
#elif defined(__GNUC__) || defined(__clang__)
#define TAMGA_API __attribute__((visibility("default")))
#else
#define TAMGA_API
#endif

/*
 * Library version, matching the git tag and the CMake project version.
 * The trailing markers are what release-please rewrites on a release; do not
 * edit these by hand or the three places the version appears will drift.
 *
 * Formatting is off across this block on purpose. clang-format aligns
 * trailing comments to the longest line, and release-please rewrites the
 * version in place without re-aligning anything -- so the first release that
 * changes the string's width (1.9.0 to 1.10.0, say) would leave the file
 * unformatted and break the format check on main, at the one moment nobody is
 * looking at a diff.
 */
/* clang-format off */
#define TAMGA_VERSION_MAJOR 1 /* x-release-please-major */
#define TAMGA_VERSION_MINOR 3 /* x-release-please-minor */
#define TAMGA_VERSION_PATCH 0 /* x-release-please-patch */
#define TAMGA_VERSION_STRING "1.3.0" /* x-release-please-version */
/* clang-format on */

#ifdef __cplusplus
extern "C" {
#endif

/* ======================================================================
 * Error codes
 * ====================================================================== */

/**
 * Error codes returned by every `tamga_*` function.
 *
 * `TAMGA_OK` (0) means success; every other value has a corresponding
 * detailed message retrievable via tamga_last_error_message() on the calling
 * thread.
 *
 * Values 0-11 are frozen from v1.0-v1.2. New codes are appended.
 */
typedef enum TamgaErrorCode {
    /** Success. */
    TAMGA_OK = 0,
    /** `-----BEGIN ...-----`/`-----END ...-----` PEM markers missing or malformed. */
    TAMGA_ERR_INVALID_PEM = 1,
    /** A base64-encoded field failed to decode. */
    TAMGA_ERR_INVALID_BASE64 = 2,
    /** Decoded bytes were not valid JSON, or didn't match the expected shape. */
    TAMGA_ERR_INVALID_JSON = 3,
    /**
     * Signature verification failed (wrong key, tampered payload, or the
     * base64-string-vs-decoded-bytes gotcha -- see CLAUDE.md).
     */
    TAMGA_ERR_SIGNATURE_INVALID = 4,
    /** AES-256-GCM open failed (wrong key/nonce, or tampered ciphertext/tag). */
    TAMGA_ERR_DECRYPTION_FAILED = 5,
    /**
     * `alg`/`scheme` value not supported by this operation (e.g.
     * `RSA_2048_JWT_RS256` for machine files, an offline licence file that is
     * not format v2, or an unrecognized offline-proof version prefix).
     */
    TAMGA_ERR_UNSUPPORTED_SCHEME = 6,
    /** A required pointer argument was null. */
    TAMGA_ERR_NULL_ARGUMENT = 7,
    /**
     * An internal invariant was violated. Retained from v1.x, where it
     * reported a Rust panic caught at the FFI boundary. The native
     * implementation has no unwinding to catch, so this is now reserved for
     * genuine internal-consistency failures and should never be observed.
     */
    TAMGA_ERR_PANIC = 8,
    /** Unclassified internal error. */
    TAMGA_ERR_UNKNOWN = 9,
    /**
     * A length-carrying argument (e.g. `pem_len`, `pubkey_len`) was zero or
     * exceeded the 16 MiB input cap -- distinct from
     * `TAMGA_ERR_NULL_ARGUMENT`, which is reserved for an actual null
     * pointer.
     */
    TAMGA_ERR_LENGTH_INVALID = 10,
    /**
     * The file's signature verified, but its signed `exp` claim is in the
     * past -- an authentic licence file that has simply run out. Check out a
     * fresh one.
     *
     * Distinct from `TAMGA_ERR_SIGNATURE_INVALID` on purpose: a caller that
     * cannot tell "expired" from "forged" either nags the user about
     * tampering when their trial ended, or treats a forgery as a renewal
     * prompt.
     */
    TAMGA_ERR_EXPIRED = 11,
    /** Memory allocation failed. */
    TAMGA_ERR_OUT_OF_MEMORY = 12,

    /* --- HTTP client, added in 1.3 ------------------------------------
     *
     * Appended after the offline codes, never interleaved with them. A
     * caller built against an older header sees only the codes it knows and
     * treats these as unrecognized failures, which is the correct outcome.
     */

    /** The request could not be completed: connection, timeout, or TLS. */
    TAMGA_ERR_TRANSPORT = 13,
    /**
     * This build has no HTTP backend and none was registered. The offline
     * surface is unaffected; register a transport with
     * tamga_client_set_transport() to use the client.
     */
    TAMGA_ERR_NO_TRANSPORT = 14,
    /** The server returned an error this SDK has no dedicated code for.
     *  tamga_response_error_code() carries the server's own string. */
    TAMGA_ERR_API = 15,
    /**
     * `429 Too Many Requests`, after the retry budget was spent. The
     * server's `Retry-After` is available via tamga_response_header().
     */
    TAMGA_ERR_RATE_LIMITED = 16,
    /** `401`: no credential was accepted. Distinct from FORBIDDEN --
     *  a missing credential and an insufficient one are different states. */
    TAMGA_ERR_UNAUTHORIZED = 17,
    /** `403`: the credential is valid but not permitted here. */
    TAMGA_ERR_FORBIDDEN = 18,
    /** `404`. */
    TAMGA_ERR_NOT_FOUND = 19,
    /** `5xx`. */
    TAMGA_ERR_SERVER = 20,
    /**
     * The licence's policy has `require_check_in: false`. This is a caller
     * error, not a transient failure -- check the policy before scheduling
     * periodic check-ins rather than retrying.
     */
    TAMGA_ERR_CHECK_IN_NOT_REQUIRED = 21,
    /** Encrypted checkout was requested for a licence with no key set. */
    TAMGA_ERR_LICENSE_NOT_ENCRYPTED = 22,
    /** Encrypted checkout was requested but the licence key is missing. */
    TAMGA_ERR_LICENSE_KEY_MISSING = 23,
    /** The requested ttl is outside the accepted range (1 second to 365 days). */
    TAMGA_ERR_TTL_INVALID = 24,
    /** The licence's scheme is not supported for this operation. */
    TAMGA_ERR_SCHEME_NOT_SUPPORTED = 25,
    /** A machine or component with this fingerprint already exists. */
    TAMGA_ERR_FINGERPRINT_TAKEN = 26,
    /** The supplied dataset is not a JSON object. */
    TAMGA_ERR_DATASET_INVALID = 27,
    /** A process with this pid already exists on the machine. */
    TAMGA_ERR_PID_TAKEN = 28
} TamgaErrorCode;

/* ======================================================================
 * Signing schemes
 * ====================================================================== */

/**
 * Signing/key scheme, mirroring the wire `LicenseScheme` strings the server
 * uses. Present for completeness -- `TAMGA_SCHEME_RSA_2048_JWT_RS256` is
 * never a legal input for machine files; it is rejected outright (`422
 * SCHEME_NOT_SUPPORTED` is what the server itself does for this scheme at
 * machine-file-checkout time).
 */
typedef enum TamgaScheme {
    /** Legacy unsigned key string. Not a valid verification scheme. */
    TAMGA_SCHEME_NONE = 0,
    TAMGA_SCHEME_ED25519_SIGN = 1,
    TAMGA_SCHEME_RSA_2048_PKCS1_SIGN = 2,
    TAMGA_SCHEME_RSA_2048_PKCS1_PSS_SIGN = 3,
    TAMGA_SCHEME_ECDSA_P256_SIGN = 4,
    /** Explicitly rejected for machine-file verification. */
    TAMGA_SCHEME_RSA_2048_JWT_RS256 = 5
} TamgaScheme;

/* ======================================================================
 * Opaque handles
 * ====================================================================== */

/**
 * Opaque handle wrapping a verified/decoded `.lic` licence-file payload.
 *
 * Obtained from tamga_license_file_verify(); must be freed with
 * tamga_license_file_free() exactly once.
 */
typedef struct TamgaLicenseFile TamgaLicenseFile;

/**
 * Opaque handle wrapping a verified/decoded machine-file payload.
 *
 * Obtained from tamga_machine_file_verify(); must be freed with
 * tamga_machine_file_free() exactly once.
 */
typedef struct TamgaMachineFile TamgaMachineFile;

/* ======================================================================
 * Diagnostics and memory
 * ====================================================================== */

/**
 * Returns the detailed message behind the last non-`TAMGA_OK` code returned
 * on the calling thread.
 *
 * Ownership: the returned pointer is **borrowed**, not owned. It is valid
 * only until the next `tamga_*` call on this same thread. Do not call
 * tamga_string_free() on it, and do not retain it across calls -- copy the
 * string out immediately if you need it to outlive the next call.
 *
 * Returns NULL if no error has been recorded yet on this thread, or if the
 * most recent call succeeded. `TAMGA_OK` always implies NULL here, with no
 * exceptions -- including tamga_offline_proof_verify(), whose `*out_valid`
 * out-parameter (not this accessor) is the correct signal for "the proof did
 * not verify", which is not itself a call failure.
 *
 * The message never contains secret material: no licence key, API token, or
 * password is ever formatted into it.
 */
TAMGA_API const char *tamga_last_error_message(void);

/**
 * Returns the human-readable name of an error code (e.g. "TAMGA_ERR_EXPIRED"),
 * or "TAMGA_ERR_UNKNOWN" for an unrecognized value.
 *
 * The returned pointer is a static string constant: it is valid forever and
 * must not be freed.
 */
TAMGA_API const char *tamga_error_name(TamgaErrorCode code);

/**
 * Frees a string previously returned as an **owned** pointer by this library
 * (decoded JSON payloads, proof strings -- anything documented as
 * caller-owned).
 *
 * Calling this on a null pointer is a documented no-op, not a crash.
 *
 * Safety: `ptr` must be null, or a pointer previously returned by this
 * library and not already freed. Calling this twice on the same pointer, or
 * calling libc free() on a pointer this library returned, is undefined
 * behavior and intentionally not guarded against.
 */
TAMGA_API void tamga_string_free(char *ptr);

/* ======================================================================
 * Key derivation
 * ====================================================================== */

/**
 * Derives the 32-byte AES key for an encrypted machine file via HKDF-SHA256:
 * `salt = "tamga:machine-file-key-v1"`, `ikm = license_key`,
 * `info = fingerprint`.
 *
 * This is NOT interchangeable with tamga_hkdf_derive_license_file_key():
 * different salt, different info. Using one where the other belongs produces
 * a function that compiles, looks plausible, and silently decrypts nothing.
 *
 * Parameters:
 * - `license_key` / `fingerprint`: NUL-terminated C strings; both required.
 * - `out_32_bytes`: receives exactly 32 derived bytes on `TAMGA_OK`.
 *
 * Safety: `out_32_bytes` must point to at least 32 writable bytes.
 */
TAMGA_API enum TamgaErrorCode tamga_hkdf_derive_machine_file_key(const char *license_key,
                                                                 const char *fingerprint,
                                                                 uint8_t *out_32_bytes);

/**
 * Derives the 32-byte AES key for an encrypted licence file via HKDF-SHA256:
 * `salt = "tamga:license-file-key-v1"`, `ikm = license_key`,
 * `info = "license-file"`.
 *
 * Parameters:
 * - `license_key`: NUL-terminated C string.
 * - `out_32_bytes`: receives exactly 32 derived bytes on `TAMGA_OK`.
 *
 * Safety: `out_32_bytes` must point to at least 32 writable bytes.
 */
TAMGA_API enum TamgaErrorCode tamga_hkdf_derive_license_file_key(const char *license_key,
                                                                 uint8_t *out_32_bytes);

/* ======================================================================
 * Licence file (.lic)
 * ====================================================================== */

/**
 * Verifies and decodes a `.lic` licence file, fully offline.
 *
 * The file must be offline format v2 (`alg` ending in `+v2`); v1 files are
 * rejected with `TAMGA_ERR_UNSUPPORTED_SCHEME` and there is no fallback path.
 * The signed `exp` claim is enforced with a 60-second clock-skew tolerance
 * and reported as `TAMGA_ERR_EXPIRED`.
 *
 * Licence-file checkout is Ed25519-only, independent of the licence's own
 * `scheme` field.
 *
 * Parameters:
 * - `pem` / `pem_len`: the raw `.lic` file bytes, PEM markers included. Need
 *   not be NUL-terminated; `pem_len` is authoritative.
 * - `ed25519_pubkey`: the account's 32-byte Ed25519 public key.
 * - `license_key`: NUL-terminated C string, or null. Required (non-null) only
 *   when the file's `alg` is `"aes-256-gcm+ed25519+v2"` (encrypted); ignored
 *   for `"base64+ed25519+v2"` (plain) files.
 * - `out_handle`: on `TAMGA_OK`, receives an owned handle; free it with
 *   tamga_license_file_free() exactly once.
 */
TAMGA_API enum TamgaErrorCode tamga_license_file_verify(const char *pem, uintptr_t pem_len,
                                                        const uint8_t *ed25519_pubkey,
                                                        const char *license_key,
                                                        struct TamgaLicenseFile **out_handle);

/**
 * Exposes the decoded licence resource as an owned JSON C string.
 *
 * The string written to `*out_ptr` is owned by the caller; free it with
 * tamga_string_free(). `*out_len` receives its length in bytes, excluding the
 * terminating NUL.
 */
TAMGA_API enum TamgaErrorCode tamga_license_file_get_json(const struct TamgaLicenseFile *handle,
                                                          char **out_ptr, uintptr_t *out_len);

/**
 * Frees a handle obtained from tamga_license_file_verify().
 *
 * Safety: `handle` must be null, or a live pointer previously returned by
 * tamga_license_file_verify() and not already freed. Double-free is
 * documented undefined behavior and intentionally unguarded.
 */
TAMGA_API void tamga_license_file_free(struct TamgaLicenseFile *handle);

/* ======================================================================
 * Machine file (.mach)
 * ====================================================================== */

/**
 * Verifies and decodes a machine file, dispatching the signature algorithm
 * from `scheme` (the licence's `scheme` field).
 *
 * The algorithm is selected from this parameter and never from the file's own
 * self-declared `alg` string: `RSA_2048_PKCS1_SIGN` and
 * `RSA_2048_JWT_RS256` share one `alg` suffix server-side, so the file cannot
 * disambiguate them -- and letting untrusted input choose a cryptographic
 * primitive is algorithm confusion regardless.
 *
 * Parameters:
 * - `pem` / `pem_len`: the raw machine-file bytes, PEM markers included.
 * - `scheme`: a raw TamgaScheme discriminant, passed as `uint32_t` rather
 *   than the enum type. A C enum has no validity range at the ABI level, so
 *   an out-of-range value from a stale header or a buggy binding must be
 *   validated before use rather than trusted. Any value outside the declared
 *   range, plus `TAMGA_SCHEME_RSA_2048_JWT_RS256` and `TAMGA_SCHEME_NONE`,
 *   is rejected with `TAMGA_ERR_UNSUPPORTED_SCHEME`.
 * - `pubkey` / `pubkey_len`: the public key matching `scheme`. Ed25519: 32
 *   raw bytes. RSA (either variant): DER, in either the PKCS#1 RSAPublicKey
 *   encoding the Tamga server uses or the SubjectPublicKeyInfo encoding
 *   OpenSSL-based tooling produces -- both are accepted. ECDSA P-256: a
 *   65-byte uncompressed point, or a SubjectPublicKeyInfo.
 * - `license_key` / `fingerprint`: required only to decrypt an encrypted
 *   (`aes-256-gcm`) machine file; ignored for plain files.
 * - `out_handle`: on `TAMGA_OK`, receives an owned handle; free it with
 *   tamga_machine_file_free() exactly once.
 */
TAMGA_API enum TamgaErrorCode
tamga_machine_file_verify(const char *pem, uintptr_t pem_len, uint32_t scheme,
                          const uint8_t *pubkey, uintptr_t pubkey_len, const char *license_key,
                          const char *fingerprint, struct TamgaMachineFile **out_handle);

/**
 * Exposes the decoded machine resource as an owned JSON C string. Same
 * ownership contract as tamga_license_file_get_json().
 */
TAMGA_API enum TamgaErrorCode tamga_machine_file_get_json(const struct TamgaMachineFile *handle,
                                                          char **out_ptr, uintptr_t *out_len);

/**
 * Frees a handle obtained from tamga_machine_file_verify(). Same contract as
 * tamga_license_file_free().
 */
TAMGA_API void tamga_machine_file_free(struct TamgaMachineFile *handle);

/* ======================================================================
 * Machine offline proof
 * ====================================================================== */

/**
 * Verifies a `"v1x0.<base64 signature>"` offline proof string against the
 * exact canonical JSON the server signed.
 *
 * Always RSA-2048 PKCS#1 v1.5 / SHA-256, regardless of the licence's own
 * `scheme` field.
 *
 * Parameters:
 * - `proof_str`: the full `"v1x0.<base64 signature>"` string.
 * - `rsa_pubkey` / `rsa_pubkey_len`: the account's RSA-2048 public key as
 *   DER, in either the PKCS#1 RSAPublicKey or the SubjectPublicKeyInfo
 *   encoding.
 * - `account_id`, `machine_id`: UUID strings.
 * - `fingerprint`: the machine's fingerprint.
 * - `dataset_json`: the client dataset as a JSON string. It is re-serialized
 *   canonically (object keys sorted by UTF-8 byte order at every nesting
 *   level) to reproduce the server's exact signed bytes.
 * - `out_valid`: on `TAMGA_OK`, receives whether the proof is valid.
 *   Distinguish "the call failed" (non-`TAMGA_OK` return) from "the call
 *   succeeded but the proof is invalid" (`TAMGA_OK` + `*out_valid == false`)
 *   -- callers must check both.
 */
TAMGA_API enum TamgaErrorCode
tamga_offline_proof_verify(const char *proof_str, const uint8_t *rsa_pubkey,
                           uintptr_t rsa_pubkey_len, const char *account_id, const char *machine_id,
                           const char *fingerprint, const char *dataset_json, bool *out_valid);

/**
 * Generates a `"v1x0.<base64 signature>"` offline proof locally.
 *
 * **Not implemented**, and deliberately so. Proof generation is a server-side
 * operation (`POST .../machines/{id}/actions/generate-offline-proof`); this
 * SDK is a client that verifies server-issued material and holds no signing
 * keys. Adding a local RSA private-key operation would be the single
 * highest-risk primitive in the library for no protocol benefit.
 *
 * Use tamga_client_generate_offline_proof() instead, which performs the real
 * server call. This entry point returns `TAMGA_ERR_UNKNOWN` with an
 * explanatory last-error message, and exists only to keep the v1.x ABI
 * intact.
 */
TAMGA_API enum TamgaErrorCode
tamga_offline_proof_generate(const char *rsa_privkey, const char *account_id,
                             const char *machine_id, const char *fingerprint,
                             const char *dataset_json, char **out_proof_str);

/* ======================================================================
 * HTTP client
 *
 * Everything above this point works with no network access and no
 * dependencies. Everything below needs a transport: either the one this
 * build was configured with (WinHTTP on Windows, libcurl elsewhere) or one
 * the caller registers. A build configured with TAMGA_HTTP=none still
 * compiles and exports all of it -- calls simply return
 * TAMGA_ERR_NO_TRANSPORT until a transport is registered.
 *
 * Structured inputs and outputs are JSON text. That is a deliberate choice
 * for a C API: mirroring every server resource as a struct would freeze a
 * large surface into the ABI and force a release whenever the server adds a
 * field, while a JSON string stays correct as the protocol grows. The
 * accessors below cover the fields callers act on programmatically.
 * ====================================================================== */

/** An API client. Not thread-safe; use one per thread, or synchronise. */
typedef struct TamgaClient TamgaClient;

/** The result of an endpoint call, successful or not. */
typedef struct TamgaResponse TamgaResponse;

/**
 * How to authenticate. The server accepts five transports; the Cookie form is
 * deliberately unsupported, being browser-only and requiring a matching
 * Origin.
 *
 * `TAMGA_AUTH_LICENSE` is the primary choice for software embedding this SDK:
 * it authenticates with the end user's own licence key. Note that the
 * licence's policy must have `authentication_strategy` set to `LICENSE` or
 * `MIXED`; the default `TOKEN` yields 401 LICENSE_NOT_ALLOWED, which is a
 * provisioning matter rather than an SDK fault.
 */
typedef enum TamgaAuthKind {
    /** `Authorization: Bearer <token>` -- preferred for server-side callers. */
    TAMGA_AUTH_BEARER = 0,
    /** `Authorization: License <key>` -- preferred for embedded callers. */
    TAMGA_AUTH_LICENSE = 1,
    /** `Authorization: Basic base64(email:password)`. */
    TAMGA_AUTH_BASIC_EMAIL_PASSWORD = 2,
    /** `Authorization: Basic base64(token:)`. */
    TAMGA_AUTH_BASIC_TOKEN = 3,
    /** `Authorization: Basic base64(license:<key>)`. */
    TAMGA_AUTH_BASIC_LICENSE = 4,
    /** `?token=<token>`, for a caller that cannot set a header. */
    TAMGA_AUTH_QUERY_TOKEN = 5
} TamgaAuthKind;

/**
 * A caller-supplied transport.
 *
 * Called with the fully-built request. Report the outcome through the
 * `tamga_http_result_*` functions and return true; return false only when the
 * request could not be made at all. Any HTTP status, including 4xx and 5xx,
 * is a successful transport call -- interpreting it is this library's job.
 *
 * Whatever you build on must verify TLS certificates and hostnames. This
 * library offers no way to disable that in its own backends and assumes the
 * same of yours.
 */
typedef struct TamgaHttpResult TamgaHttpResult;

typedef bool (*TamgaHttpFn)(void *user_data, const char *method, const char *url,
                            const char *const *header_names, const char *const *header_values,
                            uintptr_t header_count, const char *body, uintptr_t body_len,
                            unsigned int timeout_ms, TamgaHttpResult *result);

TAMGA_API void tamga_http_result_set_status(TamgaHttpResult *result, int status);
TAMGA_API bool tamga_http_result_set_body(TamgaHttpResult *result, const char *body,
                                          uintptr_t body_len);
TAMGA_API bool tamga_http_result_add_header(TamgaHttpResult *result, const char *name,
                                            const char *value);

/* --- lifecycle and configuration --------------------------------------- */

/**
 * Creates a client for one account.
 *
 * `host` may be a bare hostname, a hostname with a trailing slash, or a full
 * URL. An explicit `http://` is preserved rather than upgraded -- production
 * is always HTTPS, but this keeps the client usable against a local mock
 * server without a separate code path.
 *
 * Credentials must be set with tamga_client_set_auth() before any request.
 */
TAMGA_API TamgaErrorCode tamga_client_new(const char *account_id, const char *host,
                                          TamgaClient **out_client);

TAMGA_API void tamga_client_free(TamgaClient *client);

/**
 * Sets the credentials. `primary` is the token, licence key or email;
 * `secondary` is the password, and is required only for
 * TAMGA_AUTH_BASIC_EMAIL_PASSWORD.
 */
TAMGA_API TamgaErrorCode tamga_client_set_auth(TamgaClient *client, TamgaAuthKind kind,
                                               const char *primary, const char *secondary);

/** Overrides the `Tamga-Version` header. Defaults to "1.8". */
TAMGA_API TamgaErrorCode tamga_client_set_api_version(TamgaClient *client, const char *version);

/** Overrides the per-request timeout. Defaults to 30 seconds. */
TAMGA_API TamgaErrorCode tamga_client_set_timeout_ms(TamgaClient *client, unsigned int timeout_ms);

/**
 * How many times a rate-limited request is retried before giving up.
 * Defaults to 3; zero handles 429 yourself.
 *
 * Only requests that are safe to repeat are retried: every GET, plus POST on
 * the validate, check-in, check-out and ping actions. Creates are never
 * retried, because repeating an activation can burn a second seat.
 */
TAMGA_API TamgaErrorCode tamga_client_set_max_retries(TamgaClient *client,
                                                      unsigned int max_retries);

/**
 * Registers a transport, replacing whichever one the build provides.
 * `destroy` is optional and is called with `user_data` when the client is
 * freed or the transport replaced.
 */
TAMGA_API TamgaErrorCode tamga_client_set_transport(TamgaClient *client, TamgaHttpFn perform,
                                                    void *user_data, void (*destroy)(void *));

/** True when this build has a transport compiled in. */
TAMGA_API bool tamga_has_builtin_transport(void);

/* --- response ----------------------------------------------------------- */

TAMGA_API void tamga_response_free(TamgaResponse *response);

/** The HTTP status code. */
TAMGA_API int tamga_response_status(const TamgaResponse *response);

/**
 * The response body. For every endpoint but the raw checkouts this is JSON;
 * for those it is the PEM certificate itself. Borrowed -- valid until the
 * response is freed.
 */
TAMGA_API const char *tamga_response_json(const TamgaResponse *response, uintptr_t *out_len);

/** A response header by name, case-insensitively. Borrowed. */
TAMGA_API const char *tamga_response_header(const TamgaResponse *response, const char *name);

/**
 * The server's own error code (`NOT_FOUND`, `FINGERPRINT_TAKEN`, ...) on a
 * failed call, or NULL. Borrowed.
 */
TAMGA_API const char *tamga_response_error_code(const TamgaResponse *response);

/** Whether a validation response reports the licence as valid. */
TAMGA_API bool tamga_response_validation_is_valid(const TamgaResponse *response);

/**
 * The validation outcome code (`VALID`, `EXPIRED`, `TOO_MANY_MACHINES`, ...).
 * Match on this, never on the detail string, which is prose and may be
 * reworded. Borrowed.
 */
TAMGA_API const char *tamga_response_validation_code(const TamgaResponse *response);

/** The human-readable explanation. Borrowed. */
TAMGA_API const char *tamga_response_validation_detail(const TamgaResponse *response);

/* --- validation outcomes ------------------------------------------------ */

/**
 * The `meta.code` a validation endpoint returns.
 *
 * All 24 server-declared values are listed, but only 14 are actually
 * reachable today -- the reachable ones are marked below. The rest are
 * declared server-side for forward compatibility and never emitted; do not
 * write logic that waits for one.
 *
 * `TAMGA_VALIDATION_UNKNOWN` covers any value a future server adds. Callers
 * that need the exact string should use tamga_response_validation_code(),
 * which never loses information.
 */
typedef enum TamgaValidationCode {
    /** Reachable. All checks passed. */
    TAMGA_VALIDATION_VALID = 0,
    /** Declared, never emitted -- the handler returns 404 instead. */
    TAMGA_VALIDATION_NOT_FOUND = 1,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_BANNED = 2,
    /** Reachable. */
    TAMGA_VALIDATION_SUSPENDED = 3,
    /** Reachable. */
    TAMGA_VALIDATION_EXPIRED = 4,
    /** Reachable. Check-in is required and the window has elapsed. */
    TAMGA_VALIDATION_OVERDUE = 5,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_ENTITLEMENTS_MISSING = 6,
    /** Reachable. Over the policy's machine limit. */
    TAMGA_VALIDATION_TOO_MANY_MACHINES = 7,
    /** Reachable. */
    TAMGA_VALIDATION_TOO_MANY_CORES = 8,
    /** Reachable. */
    TAMGA_VALIDATION_TOO_MUCH_MEMORY = 9,
    /** Reachable. */
    TAMGA_VALIDATION_TOO_MUCH_DISK = 10,
    /** Reachable. */
    TAMGA_VALIDATION_TOO_MANY_PROCESSES = 11,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_TOO_MANY_USERS = 12,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_HEARTBEAT_DEAD = 13,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_HEARTBEAT_NOT_STARTED = 14,
    /** Reachable. */
    TAMGA_VALIDATION_PRODUCT_SCOPE_MISMATCH = 15,
    /** Reachable. */
    TAMGA_VALIDATION_POLICY_SCOPE_MISMATCH = 16,
    /** Reachable. */
    TAMGA_VALIDATION_USER_SCOPE_MISMATCH = 17,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_FINGERPRINT_SCOPE_MISMATCH = 18,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_COMPONENTS_SCOPE_MISMATCH = 19,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_CHECKSUM_SCOPE_MISMATCH = 20,
    /** Declared, not wired into any validation path. */
    TAMGA_VALIDATION_VERSION_SCOPE_MISMATCH = 21,
    /** Reachable. */
    TAMGA_VALIDATION_ENVIRONMENT_SCOPE_MISMATCH = 22,
    /** Reachable. Strictly `uses >= max_uses`, whatever the overage strategy. */
    TAMGA_VALIDATION_TOO_MANY_USES = 23,
    /** Any value this SDK does not recognise, including future additions. */
    TAMGA_VALIDATION_UNKNOWN = 24
} TamgaValidationCode;

/** Parses a wire code string. An unrecognised value yields UNKNOWN rather
 *  than failing, so a server-side addition cannot break a caller. */
TAMGA_API TamgaValidationCode tamga_validation_code_parse(const char *code);

/** The wire string for a code. Returns "UNKNOWN" for UNKNOWN. Static, never
 *  freed. */
TAMGA_API const char *tamga_validation_code_name(TamgaValidationCode code);

/** The validation code of a response, parsed. */
TAMGA_API TamgaValidationCode tamga_response_validation_code_enum(const TamgaResponse *response);

/**
 * True for the codes that mean "the licence is fine, this activation is one
 * too many": the machine, core, memory, disk and process limits. This is the
 * set tamga_client_activate_machine() reacts to when asked to undo an
 * over-limit activation.
 */
TAMGA_API bool tamga_validation_code_is_overage(TamgaValidationCode code);

/* --- licence endpoints -------------------------------------------------- */

/**
 * `POST /licenses/actions/validate-key` -- validates by raw key. No scope
 * support on this endpoint; use tamga_client_validate_by_id() for that.
 * `otp` may be NULL unless the account has 2FA enabled.
 */
TAMGA_API TamgaErrorCode tamga_client_validate_by_key(TamgaClient *client, const char *license_key,
                                                      const char *otp,
                                                      TamgaResponse **out_response);

/**
 * `POST /licenses/{id}/actions/validate` -- validates by id, optionally
 * scoped.
 *
 * `scope_json` is the scope object as JSON, or NULL. Only `product`, `policy`,
 * `user` and `environment` are enforced server-side today; `entitlements`,
 * `fingerprint`, `version` and `checksum` are parsed and ignored, so do not
 * rely on them as constraints.
 *
 * `skip_touch` suppresses the `last_validated_at` side effect.
 */
TAMGA_API TamgaErrorCode tamga_client_validate_by_id(TamgaClient *client, const char *license_id,
                                                     const char *scope_json, bool skip_touch,
                                                     const char *otp, TamgaResponse **out_response);

/**
 * `GET /licenses/{id}/actions/validate` -- returns only the flat
 * `{ ts, valid, detail, code }` outcome, with no licence resource. Cheaper
 * than a full validation when only the verdict is needed.
 */
TAMGA_API TamgaErrorCode tamga_client_quick_validate(TamgaClient *client, const char *license_id,
                                                     const char *otp, TamgaResponse **out_response);

/**
 * `POST /licenses/{id}/actions/check-in`.
 *
 * Fails with TAMGA_ERR_CHECK_IN_NOT_REQUIRED when the policy does not require
 * check-in. That is a caller error, not a transient failure -- read the
 * policy before scheduling periodic check-ins rather than retrying.
 */
TAMGA_API TamgaErrorCode tamga_client_check_in(TamgaClient *client, const char *license_id,
                                               TamgaResponse **out_response);

/**
 * `GET /licenses/{id}/actions/check-out` -- the raw `.lic` PEM.
 *
 * Not idempotent: a fresh identifier backs each call, so two calls yield two
 * different certificates. Pass the body to tamga_license_file_verify().
 *
 * `ttl_seconds` of zero or less requests no ttl.
 */
TAMGA_API TamgaErrorCode tamga_client_check_out_license(TamgaClient *client, const char *license_id,
                                                        bool encrypt, int64_t ttl_seconds,
                                                        TamgaResponse **out_response);

/** `POST /licenses/{id}/actions/check-out` -- the JSON:API variant, carrying
 *  the certificate plus ttl/expiry/issued metadata. */
TAMGA_API TamgaErrorCode tamga_client_check_out_license_json(TamgaClient *client,
                                                             const char *license_id, bool encrypt,
                                                             int64_t ttl_seconds,
                                                             TamgaResponse **out_response);

/* --- machine endpoints -------------------------------------------------- */

/** `GET /machines/{id}/actions/check-out` -- the raw machine-file PEM. */
TAMGA_API TamgaErrorCode tamga_client_check_out_machine(TamgaClient *client, const char *machine_id,
                                                        bool encrypt, int64_t ttl_seconds,
                                                        TamgaResponse **out_response);

/** `POST /machines/{id}/actions/check-out` -- the JSON:API variant. */
TAMGA_API TamgaErrorCode tamga_client_check_out_machine_json(TamgaClient *client,
                                                             const char *machine_id, bool encrypt,
                                                             int64_t ttl_seconds,
                                                             TamgaResponse **out_response);

/**
 * `POST /machines` -- registers a machine against a licence.
 *
 * `options_json` is an optional JSON object with any of `name`, `ip`,
 * `hostname`, `platform`, `cores`, `memory`, `disk`, `metadata`.
 *
 * ⚠️ No seat limit is checked at creation time. Limits surface later, through
 * validation. The recommended activation flow is create then validate then
 * interpret the outcome -- which is what tamga_client_activate_machine()
 * does.
 */
TAMGA_API TamgaErrorCode tamga_client_create_machine(TamgaClient *client, const char *license_id,
                                                     const char *fingerprint,
                                                     const char *options_json,
                                                     TamgaResponse **out_response);

/**
 * Creates a machine and immediately validates the licence, which is the only
 * way to discover whether the activation exceeded a limit.
 *
 * With `auto_delete_on_overage`, a machine created into an over-limit
 * validation is deleted again before returning, implementing "reject
 * over-limit activation" rather than leaving an orphaned row behind. A failed
 * deletion is not surfaced -- the validation result is what the caller asked
 * for -- and any machine left behind is still visible to normal machine
 * management for manual cleanup.
 *
 * The returned response is the validation result.
 */
TAMGA_API TamgaErrorCode tamga_client_activate_machine(
    TamgaClient *client, const char *license_id, const char *fingerprint, const char *options_json,
    const char *scope_json, bool auto_delete_on_overage, TamgaResponse **out_response);

/** `POST /machines/{id}/actions/ping-heartbeat`. */
TAMGA_API TamgaErrorCode tamga_client_ping_heartbeat(TamgaClient *client, const char *machine_id,
                                                     TamgaResponse **out_response);

/** `POST /machines/{id}/actions/reset-heartbeat` -- rewinds heartbeat state
 *  to not-started. */
TAMGA_API TamgaErrorCode tamga_client_reset_heartbeat(TamgaClient *client, const char *machine_id,
                                                      TamgaResponse **out_response);

/** `DELETE /machines/{id}`. */
TAMGA_API TamgaErrorCode tamga_client_delete_machine(TamgaClient *client, const char *machine_id,
                                                     TamgaResponse **out_response);

/**
 * `POST /machines/{id}/actions/generate-offline-proof`.
 *
 * `dataset_json` must be a JSON object, or NULL for an empty one. The
 * response carries the machine resource plus `meta.proof`; pass that string,
 * with the same account/machine/fingerprint/dataset tuple, to
 * tamga_offline_proof_verify() to check it later with no network access.
 *
 * This is the supported way to obtain a proof -- see
 * tamga_offline_proof_generate(), which deliberately does not sign locally.
 */
TAMGA_API TamgaErrorCode tamga_client_generate_offline_proof(TamgaClient *client,
                                                             const char *machine_id,
                                                             const char *dataset_json,
                                                             TamgaResponse **out_response);

/* --- components, processes, entitlements -------------------------------- */

/**
 * `POST /components`.
 *
 * ⚠️ The request body is flat, not JSON:API-enveloped, unlike machine
 * creation. That asymmetry is the server's, not this SDK's.
 */
TAMGA_API TamgaErrorCode tamga_client_create_component(TamgaClient *client, const char *machine_id,
                                                       const char *fingerprint, const char *name,
                                                       const char *metadata_json,
                                                       TamgaResponse **out_response);

/**
 * `GET /machines/{id}/components` -- keyset-paginated. The response carries no
 * cursor; pass the last returned component's id as `after` for the next page.
 * `limit` of zero uses the server default; `after` may be NULL.
 */
TAMGA_API TamgaErrorCode tamga_client_list_components(TamgaClient *client, const char *machine_id,
                                                      uint32_t limit, const char *after,
                                                      TamgaResponse **out_response);

/**
 * `POST /processes` -- same flat body shape as component creation.
 *
 * Unlike a machine, a process starts alive: its heartbeat is set at creation.
 * ⚠️ The process heartbeat window is a hardcoded 30 seconds with no
 * resurrection grace period.
 */
TAMGA_API TamgaErrorCode tamga_client_create_process(TamgaClient *client, const char *machine_id,
                                                     const char *pid, const char *metadata_json,
                                                     TamgaResponse **out_response);

/** `POST /processes/{id}/actions/ping`. */
TAMGA_API TamgaErrorCode tamga_client_ping_process(TamgaClient *client, const char *process_id,
                                                   TamgaResponse **out_response);

/** `GET /licenses/{id}/entitlements` -- keyset-paginated, same shape as
 *  component listing. */
TAMGA_API TamgaErrorCode tamga_client_list_entitlements(TamgaClient *client, const char *license_id,
                                                        uint32_t limit, const char *after,
                                                        TamgaResponse **out_response);

/** `GET /licenses/{id}/entitlements/{entitlement_id}`. */
TAMGA_API TamgaErrorCode tamga_client_get_entitlement(TamgaClient *client, const char *license_id,
                                                      const char *entitlement_id,
                                                      TamgaResponse **out_response);

/**
 * Fetches one page of entitlements and reports whether any carries `code`.
 *
 * Matches on `code`, the stable developer-facing identifier -- never on
 * `name`, which is a display label. Fetches at most one page (`limit`,
 * defaulting to the server's maximum of 100); for a licence with more
 * entitlements than fit on one page, paginate with
 * tamga_client_list_entitlements() instead.
 */
TAMGA_API TamgaErrorCode tamga_client_has_entitlement(TamgaClient *client, const char *license_id,
                                                      const char *code, uint32_t limit,
                                                      bool *out_has);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TAMGA_H */
