/*
 * tamga.h -- C ABI for the Tamga licensing SDK's offline-verification core.
 *
 * AUTOGENERATED by cbindgen from src/lib.rs and friends. Do not hand-edit --
 * see build.rs and cbindgen.toml. Committed to the repo so downstream
 * consumers (tests/c/, examples/, tamga-java's JNI layer, tamga-swift's
 * CTamgaShim) always have a header to build against without invoking Rust
 * tooling, and so CI can diff it for freshness.
 *
 * ABI stability policy: once a version of this header has shipped in a
 * GitHub Release, struct layout and function signature changes require a
 * version bump -- no silent breaking changes. tamga-java (JNI) and
 * tamga-swift (Swift/ObjC bridge) both link against built artifacts of this
 * exact header; a deviation between what's documented here and what the
 * cdylib actually exports is a memory-safety bug in every downstream
 * consumer, not just a compile error.
 *
 * Alloc/free pairing contract: every function that returns an owned pointer
 * (tamga_*_verify, tamga_*_generate) has exactly one matching tamga_*_free.
 * Every owned `char*` this library returns (JSON payloads, error messages,
 * generated proof strings) must be released via tamga_string_free -- never
 * call libc free() directly on a Rust-allocated string. Double-free is
 * documented undefined behavior and intentionally unguarded; guarding it
 * would hide caller bugs.
 *
 * This is NOT an HTTP client. tamga-c has no auth-transport, validate,
 * check-in, or machine-management surface -- see README.md.
 */


#ifndef TAMGA_H
#define TAMGA_H

#pragma once

/* Warning: this file is autogenerated by cbindgen. Do not modify it manually — edit src/lib.rs and re-run `cargo build`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* TAMGA_H */
